package com.enigma.dynamodbcrud.entitties;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;

@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "movie")
public class Movie {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String movieId;

    @DynamoDBAttribute
    private String title;

    @DynamoDBAttribute
    private String image;

    @DynamoDBAttribute
    private String rating;

    @DynamoDBAttribute
    private String releaseYear;

    @DynamoDBAttribute
    public List<String> genre;

}
